<a href="https://colab.research.google.com/github/nurfnick/Mathematical_Musings/blob/main/LengthOfRandomProjections.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [67]:
import numpy as np
from scipy import stats
np.random.seed(42)


In [75]:
J = np.random.normal(0,scale = np.sqrt(1/5),size=[5,15])
J

array([[ 0.36756597,  0.22425451,  0.51795682,  0.11498616,  0.14065444,
         0.6135154 ,  0.07850982, -0.13831804,  0.30103088, -0.11476851,
        -0.16449666,  0.56963099, -0.1305652 , -1.18743083,  0.15452032],
       [-0.17688033, -0.12930593,  0.20255928, -0.0742647 ,  0.09612357,
        -0.90440673, -0.42174783,  0.62786944, -0.00829617, -0.74841402,
        -0.47965082, -0.44389803,  0.04577128, -0.19346875, -0.29479529],
       [ 0.00176082,  0.21365813, -0.11584113, -0.25701777, -0.18849973,
         0.15197256, -0.0033005 ,  0.34314558, -0.51420287, -0.34674085,
         0.3457591 , -0.35858831,  0.61895065,  0.62842692,  0.62266701],
       [-0.39383455,  0.03438847, -0.22066971,  0.41285087,  0.76321694,
         0.39068106,  0.00408948, -0.16347414,  0.29028041, -0.54688567,
         0.23985677, -0.40906222,  0.2775176 , -0.07197338, -0.17363712],
       [-0.39601317, -0.15954123,  0.24870523,  0.46682866,  0.23543478,
         0.6099486 ,  1.13554809, -0.14511677, 

In [76]:
P = np.transpose(J)@J
np.size(P)

225

In [77]:
x = np.random.random(size = 15)
x

array([0.08413996, 0.16162871, 0.89855419, 0.60642906, 0.00919705,
       0.10147154, 0.66350177, 0.00506158, 0.16080805, 0.54873379,
       0.6918952 , 0.65196126, 0.22426931, 0.71217922, 0.23724909])

In [78]:
J@x

array([ 0.12196362, -1.49709376,  0.25454148, -0.31131641,  1.88221281])

In [79]:
x.dot(x)

3.50352403153792

In [80]:
(J@x).dot(J@x)

5.960599178342913

In [81]:
(np.linalg.norm(J@x))**2

5.960599178342913

So the theorem here says that the expected value of $E\left[\|Jx\|^2\right]$ should be equal to $\|x\|^2$  Using the normal distribution centered at 0 with a variance of $\frac1k$ was important here too!  Let's preform a Monte Carlo simulation.

In [85]:
list = []
for i in range(100):
  J = np.random.normal(0,scale = np.sqrt(1/5),size=[5,15])
  list.append((J@x).dot(J@x))
np.mean(list)



3.35293140328717

3.70574528699684

In [86]:
list

[5.401373833103554,
 3.079757312530403,
 2.7161063149947555,
 0.848804568278809,
 1.6024911624488174,
 2.862999993836489,
 7.65229969038855,
 2.8184943077257514,
 3.7244006730415857,
 1.7667271791578336,
 7.392685351759348,
 5.307608887922622,
 2.8180636310908636,
 1.1906239007827994,
 5.526099960942098,
 2.16115979128065,
 2.5173476626701805,
 6.168329328885976,
 4.064610808804924,
 3.738495858675611,
 8.368170717278385,
 1.6569631567505347,
 3.5462781652593818,
 0.4384188511791657,
 2.3033612879892975,
 4.0286263495528125,
 5.578661093546842,
 0.4345697176645603,
 3.323360403315484,
 4.629638368043372,
 3.9367684047436624,
 2.3991497583080412,
 2.1258311988946326,
 1.2530754485943851,
 2.8201638239441404,
 3.6851475911973157,
 1.4238104183320524,
 1.4278549447766185,
 3.2736826381534665,
 1.1270326809426772,
 2.9228910018337113,
 1.5653606484551938,
 3.4959152375400717,
 2.283161216924296,
 11.81013487816218,
 7.646522512910454,
 2.382799330163689,
 0.8454658268184848,
 4.06406700927